/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ContasaPagar;

import javax.swing.JOptionPane;

/**
 *
 * @author hugao
 */
public class CONTASAPAGAR extends javax.swing.JFrame {

    /**
     * Creates new form CONTASAPAGAR
     */
    public CONTASAPAGAR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbDescricaodaConta = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        lbDataPagamento = new javax.swing.JLabel();
        lbForncedor = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbStatusPagamento = new javax.swing.JLabel();
        lbMetodoPagamento = new javax.swing.JLabel();
        lbObservacoes = new javax.swing.JLabel();
        txtfDescricaodaConta = new javax.swing.JTextField();
        txtfValor = new javax.swing.JTextField();
        txtfDataVencimento = new javax.swing.JTextField();
        txtfDataPagamento = new javax.swing.JTextField();
        txtfFornecedor = new javax.swing.JTextField();
        txtfCategoria = new javax.swing.JTextField();
        txtfStatusPagamento = new javax.swing.JTextField();
        txtfMetodoPagamento = new javax.swing.JTextField();
        txtfObservacoes = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lbCodcontasapagar = new javax.swing.JLabel();
        txtfCodcontasapagar = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnrelatorio = new javax.swing.JMenu();
        btnDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbDescricaodaConta.setText("Descrição da Conta");

        lbValor.setText("Valor");

        lbDataNascimento.setText("Data Vencimento");

        lbDataPagamento.setText("Data Pagamento");

        lbForncedor.setText("Fornecedor");

        lbCategoria.setText("Categoria");

        lbStatusPagamento.setText("Status Pagamento");

        lbMetodoPagamento.setText("Método Pagamento");

        lbObservacoes.setText("Observações ");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lbCodcontasapagar.setText("Codcontasapagar");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnrelatorio.setText("Relatorio");

        btnDados.setText("Dados");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        btnrelatorio.add(btnDados);

        jMenuBar1.add(btnrelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCodcontasapagar)
                    .addComponent(lbObservacoes)
                    .addComponent(lbMetodoPagamento)
                    .addComponent(lbStatusPagamento)
                    .addComponent(lbCategoria)
                    .addComponent(lbForncedor)
                    .addComponent(lbDataPagamento)
                    .addComponent(lbDataNascimento)
                    .addComponent(lbValor)
                    .addComponent(lbDescricaodaConta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDescricaodaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfCodcontasapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnMostrar)
                        .addGap(41, 41, 41)
                        .addComponent(btnGravar)
                        .addGap(40, 40, 40)
                        .addComponent(btnAtualizar)
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluir)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCodcontasapagar)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtfCodcontasapagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricaodaConta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDescricaodaConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbValor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDataVencimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataPagamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDataPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbForncedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCategoria)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStatusPagamento)
                    .addComponent(txtfStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMetodoPagamento)
                    .addComponent(txtfMetodoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbObservacoes)
                    .addComponent(txtfObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        
      Limpar();  
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        contaapagar_ cn = this.MontarContaaPagar();
        JOptionPane.showMessageDialog(null, "DescricaodaConta: "+cn.getDescricao_da_Conta()+"\nValor: "+cn.getValor()+
        "\nDataVencimento: "+cn.getData_Vencimento()+"\nDataPagamento: "+cn.getData_Pagamento()+
        "\nFornecedor: "+cn.getFornecedor()+"\nCategoria: "+cn.getCategoria()+"\nStatusPagamento: "+cn.getStatus_Pagamento()+
        "\nMetodoPagamento: "+cn.getMetodo_Pagamento()+"\nObservacoes: "+cn.getObservacoes());
        
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        contaapagar_ c = this.MontarContaaPagar();
         if  (c != null) {
             ContasaPagarControle cp = new ContasaPagarControle ();
             cp.insert(c);
        }else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos: ");
        
        }           
                        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        contaapagar_ c = this.MontarContaaPagar();
        if  (c != null && !txtfCodcontasapagar.getText().trim().isEmpty()){
             c.setCodcontaapagar_(Integer.parseInt(txtfCodcontasapagar.getText()));
             ContasaPagarControle cp = new ContasaPagarControle ();
             cp.update(c);
        }else {
              JOptionPane.showMessageDialog(null, "Preencha todos os campos.");     
        }  
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ContasaPagarControle cp = new ContasaPagarControle ();
        if(!txtfCodcontasapagar.getText().trim().isEmpty()){
            int Cod = Integer.parseInt(txtfCodcontasapagar.getText());
            cp.delete(Cod);
         }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");    
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        ContasaPagarControle cp = new ContasaPagarControle ();
        cp.selectall();
    }//GEN-LAST:event_btnDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void FormContaPagar () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONTASAPAGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONTASAPAGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONTASAPAGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONTASAPAGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONTASAPAGAR().setVisible(true);
            }
        });
    }
    
    public contaapagar_ MontarContaaPagar() {
       
           if (txtfDescricaodaConta.getText().trim().isEmpty() || txtfValor.getText().trim().isEmpty() || txtfDataVencimento.getText().trim().isEmpty() 
               || txtfDataPagamento.getText().trim().isEmpty() || txtfFornecedor.getText().trim().isEmpty() || txtfCategoria.getText().trim().isEmpty() 
               || txtfStatusPagamento.getText().trim().isEmpty() || txtfMetodoPagamento.getText().trim().isEmpty() || txtfObservacoes.getText().trim().isEmpty())
               
            { JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return null; 
            }
           
        try{   
           contaapagar_ cn = new contaapagar_ ();
           cn.setDescricao_da_Conta(txtfDescricaodaConta.getText().trim());
           cn.setValor(txtfValor.getText().trim());
           cn.setData_Vencimento(txtfDataVencimento.getText().trim());
           cn.setData_Pagamento(txtfDataPagamento.getText().trim());
           cn.setFornecedor(txtfFornecedor.getText().trim());
           cn.setCategoria(txtfCategoria.getText().trim());
           cn.setStatus_Pagamento(txtfStatusPagamento.getText().trim());
           cn.setMetodo_Pagamento(txtfMetodoPagamento.getText().trim());
           cn.setObservacoes(txtfObservacoes.getText().trim());
        
    return cn;    
     
         }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, " inválido. Digite.", "Erro", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
        
        public void Limpar() {
        txtfCategoria.setText("");
        txtfDataVencimento.setText("");
        txtfDataPagamento.setText("");
        txtfDescricaodaConta.setText("");
        txtfFornecedor.setText("");
        txtfMetodoPagamento.setText("");
        txtfObservacoes.setText("");
        txtfStatusPagamento.setText("");
        txtfValor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JMenuItem btnDados;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu btnrelatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCodcontasapagar;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbDataPagamento;
    private javax.swing.JLabel lbDescricaodaConta;
    private javax.swing.JLabel lbForncedor;
    private javax.swing.JLabel lbMetodoPagamento;
    private javax.swing.JLabel lbObservacoes;
    private javax.swing.JLabel lbStatusPagamento;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField txtfCategoria;
    private javax.swing.JTextField txtfCodcontasapagar;
    private javax.swing.JTextField txtfDataPagamento;
    private javax.swing.JTextField txtfDataVencimento;
    private javax.swing.JTextField txtfDescricaodaConta;
    private javax.swing.JTextField txtfFornecedor;
    private javax.swing.JTextField txtfMetodoPagamento;
    private javax.swing.JTextField txtfObservacoes;
    private javax.swing.JTextField txtfStatusPagamento;
    private javax.swing.JTextField txtfValor;
    // End of variables declaration//GEN-END:variables
}
