/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRINCIPAL;

import ALUNO.ALUNOS;
import Cliente.CLIENTE;
import ContasaPagar.CONTASAPAGAR;
import Eventos.EVENTOS;
import FUNCIONARIO.FUNCIONARIO;
import Fornecedor.FORNECEDOR;
import LIVROS.LIVROS;
import PRODUTOS.PRODUTOS;
import VEICULOS.VEICULOS;

/**
 *
 * @author Senac
 */
public class PrincipalPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPrincipal
     */
    public PrincipalPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadAluno = new javax.swing.JButton();
        btnCadCliente = new javax.swing.JButton();
        btnCadcontaspagar = new javax.swing.JButton();
        btnCadeventos = new javax.swing.JButton();
        btnCadFuncionario = new javax.swing.JButton();
        btnCadFornecedor = new javax.swing.JButton();
        btnCadLivros = new javax.swing.JButton();
        btnCadProdutos = new javax.swing.JButton();
        btnCadVeiculos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCadAluno.setText("Cadastro Aluno");
        btnCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAlunoActionPerformed(evt);
            }
        });

        btnCadCliente.setText("Cadastro Cliente");
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteActionPerformed(evt);
            }
        });

        btnCadcontaspagar.setText("Cadastro Contas Pagar");
        btnCadcontaspagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadcontaspagarActionPerformed(evt);
            }
        });

        btnCadeventos.setText("Cadastro Eventos");
        btnCadeventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadeventosActionPerformed(evt);
            }
        });

        btnCadFuncionario.setText("Cadastro Funcionario");
        btnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioActionPerformed(evt);
            }
        });

        btnCadFornecedor.setText("Cadastro Fornecedor");
        btnCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFornecedorActionPerformed(evt);
            }
        });

        btnCadLivros.setText("Cadastro Livros");
        btnCadLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadLivrosActionPerformed(evt);
            }
        });

        btnCadProdutos.setText("Cadastro Produtos");
        btnCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProdutosActionPerformed(evt);
            }
        });

        btnCadVeiculos.setText("Cadastro Veiculos");
        btnCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeiculosActionPerformed(evt);
            }
        });

        jLabel1.setText("         MENU CADASTRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadcontaspagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadeventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnCadAluno)
                .addGap(18, 18, 18)
                .addComponent(btnCadCliente)
                .addGap(18, 18, 18)
                .addComponent(btnCadcontaspagar)
                .addGap(18, 18, 18)
                .addComponent(btnCadeventos)
                .addGap(18, 18, 18)
                .addComponent(btnCadFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btnCadFornecedor)
                .addGap(18, 18, 18)
                .addComponent(btnCadLivros)
                .addGap(18, 18, 18)
                .addComponent(btnCadProdutos)
                .addGap(18, 18, 18)
                .addComponent(btnCadVeiculos)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAlunoActionPerformed
          ALUNOS fa = new ALUNOS ();
          fa.FormAlunos();
    }//GEN-LAST:event_btnCadAlunoActionPerformed

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed
          CLIENTE cl = new CLIENTE ();
          cl.FormCliente();
    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnCadcontaspagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadcontaspagarActionPerformed
          CONTASAPAGAR cp = new CONTASAPAGAR ();
          cp.FormContaPagar();
    }//GEN-LAST:event_btnCadcontaspagarActionPerformed

    private void btnCadeventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadeventosActionPerformed
          EVENTOS e = new EVENTOS () ;
          e.FormEventos();
    }//GEN-LAST:event_btnCadeventosActionPerformed

    private void btnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioActionPerformed
          FUNCIONARIO f = new FUNCIONARIO ();
          f.FormFuncionario();
       
    }//GEN-LAST:event_btnCadFuncionarioActionPerformed

    private void btnCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFornecedorActionPerformed
         FORNECEDOR fn = new FORNECEDOR ();
         fn.FormFornecedor();
    }//GEN-LAST:event_btnCadFornecedorActionPerformed

    private void btnCadLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadLivrosActionPerformed
         LIVROS l = new LIVROS ();
         l.FormLivros();
    }//GEN-LAST:event_btnCadLivrosActionPerformed

    private void btnCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProdutosActionPerformed
         PRODUTOS p = new PRODUTOS ();
         p.FormProdutos();
    }//GEN-LAST:event_btnCadProdutosActionPerformed

    private void btnCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeiculosActionPerformed
         VEICULOS v = new VEICULOS ();
         v.FormVeiculos();
    }//GEN-LAST:event_btnCadVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void MenuPrincipal () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAluno;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadFornecedor;
    private javax.swing.JButton btnCadFuncionario;
    private javax.swing.JButton btnCadLivros;
    private javax.swing.JButton btnCadProdutos;
    private javax.swing.JButton btnCadVeiculos;
    private javax.swing.JButton btnCadcontaspagar;
    private javax.swing.JButton btnCadeventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
