/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LIVROS;

import LIVROS.livros_;
import javax.swing.JOptionPane;

/**
 *
 * @author hugao
 */
public class LIVROS extends javax.swing.JFrame {

    /**
     * Creates new form LIVROS
     */
    public LIVROS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        lbISBN = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        lbAnodePublicacao = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbNumerodePaginas = new javax.swing.JLabel();
        lbIdioma = new javax.swing.JLabel();
        lbLocalizacaonaBiblioteca = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        txtfTitulo = new javax.swing.JTextField();
        txtfAutor = new javax.swing.JTextField();
        txtfISBN = new javax.swing.JTextField();
        txtfEditora = new javax.swing.JTextField();
        txtfAnodePublicacao = new javax.swing.JTextField();
        txtfGenero = new javax.swing.JTextField();
        txtfNumerodePaginas = new javax.swing.JTextField();
        txtfIdioma = new javax.swing.JTextField();
        txtfLocalizacaonaBiblioteca = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lbCodlivros = new javax.swing.JLabel();
        txtfCodlivros = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitulo.setText("Título");

        lbAutor.setText("Autor");

        lbISBN.setText("ISBN");

        lbEditora.setText("Editora");

        lbAnodePublicacao.setText("Ano de Publicação");

        lbGenero.setText("Gênero");

        lbNumerodePaginas.setText("Número de Páginas");

        lbIdioma.setText("Idioma");

        lbLocalizacaonaBiblioteca.setText("Localização na Biblioteca");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lbCodlivros.setText("Codlivros");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jMenu1.setText("Relatorio");

        btnDados.setText("Dados");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        jMenu1.add(btnDados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbIdioma)
                        .addComponent(lbLocalizacaonaBiblioteca)
                        .addComponent(lbNumerodePaginas)
                        .addComponent(lbGenero)
                        .addComponent(lbAnodePublicacao)
                        .addComponent(lbEditora)
                        .addComponent(lbISBN)
                        .addComponent(lbAutor)
                        .addComponent(lbTitulo)
                        .addComponent(lbCodlivros)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfLocalizacaonaBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfIdioma, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtfNumerodePaginas)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtfISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(txtfAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtfTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtfEditora)
                                        .addComponent(txtfAnodePublicacao))
                                    .addComponent(txtfGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfCodlivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGravar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCodlivros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfCodlivros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(txtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEditora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfEditora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAnodePublicacao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfAnodePublicacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGenero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumerodePaginas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfNumerodePaginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIdioma)
                    .addComponent(txtfIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLocalizacaonaBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfLocalizacaonaBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnGravar)
                    .addComponent(btnMostrar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnExcluir))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        livros_ l = this.MontarLivros();
        JOptionPane.showMessageDialog(null, "Titulo: "+l.getTitulo()+"\nAutor: "+l.getAutor()+
        "\nISBN: "+l.getISBN()+"\nEditora: "+l.getEditora()+"\nAnodePublicacao: "+l.getAno_Publicacao()+
        "\nGenero: "+l.getGenero()+"\nNumerodePaginas: "+l.getNumero_de_Paginas()+"\nIdioma: "+l.getIdioma()+
        "\nLocalizacaonaBiblioteca: "+l.getLocalizacao_na_Biblioteca());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        livros_ l = this.MontarLivros();
        if  (l != null) {
        LivrosControle lv = new LivrosControle();
        lv.insert(l);
        }else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos: ");
        
        }
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        livros_ l = this.MontarLivros();
           if  (l != null && !txtfCodlivros.getText().trim().isEmpty()){
                l.setCodlivros_(Integer.parseInt(txtfCodlivros.getText()));
                LivrosControle lv = new LivrosControle();
                lv.update(l);
            }else {
              JOptionPane.showMessageDialog(null, "Preencha todos os campos.");    
                
           }
        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         LivrosControle lv = new LivrosControle();
         if(!txtfCodlivros.getText().trim().isEmpty()){
                int Cod = Integer.parseInt(txtfCodlivros.getText());
                lv.delete(Cod);
             }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
       }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
        LivrosControle lv = new LivrosControle();
        lv.selectall();
    }//GEN-LAST:event_btnDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void FormLivros () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LIVROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LIVROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LIVROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LIVROS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LIVROS().setVisible(true);
            }
        });
    }

    public livros_ MontarLivros() {
          
           if (txtfTitulo.getText().trim().isEmpty() || txtfAutor.getText().trim().isEmpty() || txtfISBN.getText().trim().isEmpty() || txtfEditora.getText().trim().isEmpty() 
               || txtfAnodePublicacao.getText().trim().isEmpty() || txtfGenero.getText().trim().isEmpty() || txtfNumerodePaginas.getText().trim().isEmpty() 
               || txtfIdioma.getText().trim().isEmpty() || txtfLocalizacaonaBiblioteca.getText().trim().isEmpty())
            
             { JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return null; 
            }   
        
        try{
        
            livros_ l = new livros_ ();
            l.setTitulo(txtfTitulo.getText().trim());
            l.setAutor(txtfAutor.getText().trim());
            l.setISBN(txtfISBN.getText().trim());
            l.setEditora(txtfEditora.getText().trim());
            l.setAno_Publicacao(txtfAnodePublicacao.getText().trim());
            l.setGenero(txtfGenero.getText().trim());
            l.setNumero_de_Paginas(txtfNumerodePaginas.getText().trim());
            l.setIdioma(txtfIdioma.getText().trim());
            l.setLocalizacao_na_Biblioteca(txtfLocalizacaonaBiblioteca.getText().trim());
        
    return l;

        }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, " inválido. Digite.", "Erro", JOptionPane.ERROR_MESSAGE);
             return null;
     
           }
    }     
      
    
    
    
        public void Limpar() {
        txtfAnodePublicacao.setText("");
        txtfAutor.setText("");
        txtfEditora.setText("");
        txtfGenero.setText("");
        txtfISBN.setText("");
        txtfIdioma.setText("");
        txtfLocalizacaonaBiblioteca.setText("");
        txtfNumerodePaginas.setText("");
        txtfTitulo.setText("");
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JMenuItem btnDados;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbAnodePublicacao;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbCodlivros;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbIdioma;
    private javax.swing.JLabel lbLocalizacaonaBiblioteca;
    private javax.swing.JLabel lbNumerodePaginas;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtfAnodePublicacao;
    private javax.swing.JTextField txtfAutor;
    private javax.swing.JTextField txtfCodlivros;
    private javax.swing.JTextField txtfEditora;
    private javax.swing.JTextField txtfGenero;
    private javax.swing.JTextField txtfISBN;
    private javax.swing.JTextField txtfIdioma;
    private javax.swing.JTextField txtfLocalizacaonaBiblioteca;
    private javax.swing.JTextField txtfNumerodePaginas;
    private javax.swing.JTextField txtfTitulo;
    // End of variables declaration//GEN-END:variables

}