/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRODUTOS;

import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class PRODUTOS extends javax.swing.JFrame {

    /**
     * Creates new form PRODUTOS
     */
    public PRODUTOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeProduto = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        lbQntEstoque = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbDataValidade = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        lbLocalEstoque = new javax.swing.JLabel();
        txtfNomeProduto = new javax.swing.JTextField();
        txtfDescricao = new javax.swing.JTextField();
        txtfPreco = new javax.swing.JTextField();
        txtfQntEstoque = new javax.swing.JTextField();
        txtfCategoria = new javax.swing.JTextField();
        txtfDataValidade = new javax.swing.JTextField();
        txtfFornecedor = new javax.swing.JTextField();
        txtfLocalEstoque = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lbCodprodutos = new javax.swing.JLabel();
        txtfCodprodutos = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNomeProduto.setText("Nome Produto");

        lbDescricao.setText("Descrição");

        lbPreco.setText("Preço");

        lbQntEstoque.setText("Qnt Estoque");

        lbCategoria.setText("Categoria");

        lbDataValidade.setText("Data Validade");

        lbFornecedor.setText("Fornecedor");

        lbLocalEstoque.setText("Local Estoque");

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lbCodprodutos.setText("Codprodutos");

        jMenu1.setText("relatorio");

        btnDados.setText("Dados");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        jMenu1.add(btnDados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnMostrar)
                        .addGap(36, 36, 36)
                        .addComponent(btnGravar)
                        .addGap(40, 40, 40)
                        .addComponent(btnAtualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLocalEstoque)
                                    .addComponent(btnLimpar)
                                    .addComponent(lbFornecedor)
                                    .addComponent(lbDataValidade)
                                    .addComponent(lbCategoria)
                                    .addComponent(lbQntEstoque)
                                    .addComponent(lbPreco)
                                    .addComponent(lbDescricao))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfDescricao)
                                    .addComponent(txtfFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(txtfLocalEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfQntEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(txtfPreco)
                                    .addComponent(txtfDataValidade)
                                    .addComponent(txtfCategoria)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeProduto)
                                    .addComponent(lbCodprodutos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfCodprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodprodutos)
                    .addComponent(txtfCodprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeProduto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfNomeProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbQntEstoque, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfQntEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbCategoria)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataValidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDataValidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocalEstoque)
                    .addComponent(txtfLocalEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        produtos_ p = this.MontarProdutos();
        JOptionPane.showMessageDialog(null, "NomeProduto: "+p.getNome_Produto()+"\nDescricao: "+p.getDescricao()+
        "\nPreco: "+p.getPreco()+"\nQntEstoque: "+p.getQnt_Estoque()+"\nCategoria: "+p.getCategoria()+
        "\nDataValidade: "+p.getData_Validade()+"\nFornecedor: "+p.getFornecedor()+
        "\nLocalEstoque: "+p.getLocal_Estoque());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        produtos_ p = this.MontarProdutos();
         if  (p != null) {
        ProdutosControle pc = new ProdutosControle ();
        pc.insert(p);
        }else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos: ");
        
        }
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
          produtos_ p = this.MontarProdutos();
              if  (p != null && !txtfCodprodutos.getText().trim().isEmpty()){
                   p.setCodprodutos_(Integer.parseInt(txtfCodprodutos.getText()));
                   ProdutosControle pc = new ProdutosControle ();
                   pc.update(p);
                 }else {
              JOptionPane.showMessageDialog(null, "Preencha todos os campos.");    
                   
              }
              
                 
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
       ProdutosControle pc = new ProdutosControle ();
       pc.selectall();
    }//GEN-LAST:event_btnDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void FormProdutos () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRODUTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRODUTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRODUTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRODUTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRODUTOS().setVisible(true);
            }
        });
    }

    public produtos_ MontarProdutos() {
           
           if (txtfNomeProduto.getText().trim().isEmpty() || txtfDescricao.getText().trim().isEmpty() || txtfPreco.getText().trim().isEmpty() || txtfQntEstoque.getText().trim().isEmpty()      
               || txtfCategoria.getText().trim().isEmpty() || txtfDataValidade.getText().trim().isEmpty() || txtfFornecedor.getText().trim().isEmpty() 
               || txtfLocalEstoque.getText().trim().isEmpty())
               
            { JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return null; 
            }    
        
    try{    
        produtos_ p = new produtos_ ();
        p.setNome_Produto(txtfNomeProduto.getText().trim());
        p.setDescricao(txtfDescricao.getText().trim());
        p.setPreco(txtfPreco.getText().trim());
        p.setQnt_Estoque(txtfQntEstoque.getText().trim());
        p.setCategoria(txtfCategoria.getText().trim());
        p.setData_Validade(txtfDataValidade.getText().trim());
        p.setFornecedor(txtfFornecedor.getText().trim());
        p.setLocal_Estoque(txtfLocalEstoque.getText().trim());
        
    return p;
    
    }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, " inválido. Digite.", "Erro", JOptionPane.ERROR_MESSAGE);
            return null;
    }
}             
    
    
    public void Limpar(){
        txtfCategoria.setText("");
        txtfDataValidade.setText("");
        txtfDescricao.setText("");
        txtfFornecedor.setText("");
        txtfLocalEstoque.setText("");
        txtfNomeProduto.setText("");
        txtfPreco.setText("");
        txtfQntEstoque.setText("");
          
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JMenuItem btnDados;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCodprodutos;
    private javax.swing.JLabel lbDataValidade;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbLocalEstoque;
    private javax.swing.JLabel lbNomeProduto;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQntEstoque;
    private javax.swing.JTextField txtfCategoria;
    private javax.swing.JTextField txtfCodprodutos;
    private javax.swing.JTextField txtfDataValidade;
    private javax.swing.JTextField txtfDescricao;
    private javax.swing.JTextField txtfFornecedor;
    private javax.swing.JTextField txtfLocalEstoque;
    private javax.swing.JTextField txtfNomeProduto;
    private javax.swing.JTextField txtfPreco;
    private javax.swing.JTextField txtfQntEstoque;
    // End of variables declaration//GEN-END:variables
}
