/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Eventos;

import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class EVENTOS extends javax.swing.JFrame {

    /**
     * Creates new form EVENTOS
     */
    public EVENTOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomedoEvento = new javax.swing.JLabel();
        lbDatadoEvento = new javax.swing.JLabel();
        lbHorarioInicio = new javax.swing.JLabel();
        lbHorarioTermino = new javax.swing.JLabel();
        lbLocaldoEvento = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbPublicoAlvo = new javax.swing.JLabel();
        lbCapacidadeMaxima = new javax.swing.JLabel();
        lbOrganizador = new javax.swing.JLabel();
        txtfNomedoEvento = new javax.swing.JTextField();
        txtfDatadoEvento = new javax.swing.JTextField();
        txtfHorarioInicio = new javax.swing.JTextField();
        txtfHorarioTermino = new javax.swing.JTextField();
        txtfLocaldoEvento = new javax.swing.JTextField();
        txtfDescricao = new javax.swing.JTextField();
        txtfPublicoAlvo = new javax.swing.JTextField();
        txtfCapacidadeMaxima = new javax.swing.JTextField();
        txtfOrganizador = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        lbCodeventos = new javax.swing.JLabel();
        txtfCodeventos = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        lbNomedoEvento.setText("Nome do Evento");

        lbDatadoEvento.setText("Data do Evento");

        lbHorarioInicio.setText("Horário Início");

        lbHorarioTermino.setText("Horário Término");

        lbLocaldoEvento.setText("Local do Evento");

        lbDescricao.setText("Descrição");

        lbPublicoAlvo.setText("Público Alvo");

        lbCapacidadeMaxima.setText("Capacidade Máxima");

        lbOrganizador.setText("Organizador");

        txtfDatadoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDatadoEventoActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        lbCodeventos.setText("Codeventos");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jMenu1.setText("Relatorio");

        btnDados.setText("Dados");
        btnDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosActionPerformed(evt);
            }
        });
        jMenu1.add(btnDados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGravar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomedoEvento)
                            .addComponent(lbDatadoEvento)
                            .addComponent(lbHorarioInicio)
                            .addComponent(lbHorarioTermino)
                            .addComponent(lbLocaldoEvento)
                            .addComponent(lbPublicoAlvo)
                            .addComponent(lbCapacidadeMaxima)
                            .addComponent(lbOrganizador)
                            .addComponent(lbDescricao)
                            .addComponent(lbCodeventos))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfCodeventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtfNomedoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(txtfHorarioInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(txtfDatadoEvento)
                                .addComponent(txtfHorarioTermino)
                                .addComponent(txtfLocaldoEvento)
                                .addComponent(txtfPublicoAlvo)
                                .addComponent(txtfCapacidadeMaxima)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodeventos)
                    .addComponent(txtfCodeventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomedoEvento)
                    .addComponent(txtfNomedoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDatadoEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDatadoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHorarioInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfHorarioInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHorarioTermino, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfHorarioTermino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLocaldoEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfLocaldoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPublicoAlvo)
                    .addComponent(txtfPublicoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCapacidadeMaxima)
                    .addComponent(txtfCapacidadeMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOrganizador, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfOrganizador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnMostrar)
                    .addComponent(btnGravar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnFechar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfDatadoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDatadoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDatadoEventoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
       
      Limpar();  
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        eventos_ e = this.MontarEventos();
        JOptionPane.showMessageDialog(null, "NomedoEvento: "+e.getNome_do_Evento()+"\nDatadoEvento: "+e.getData_do_Evento()+
        "\nHorarioInicio: "+e.getHorario_Inicio()+"\nHorarioTermino: "+e.getHorario_Termino()+"\nLocaldoEvento: "+e.getLocal_do_Evento()+
        "\nDescricao: "+e.getDescricao()+"\nPublicoAlvo: "+e.getPublico_Alvo()+"\nCapacidadeMaxima: "+e.getCapacidade_Maxima()+
        "\nOrganizador: "+e.getOrganizador());
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        eventos_ e = this.MontarEventos();
         if  (e != null) {
        EventosControle ev = new EventosControle ();
        ev.insert(e);
        }else {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos: ");
        
        }
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         eventos_ e = this.MontarEventos();
         if  (e != null && !txtfCodeventos.getText().trim().isEmpty()){
             e.setCodeventos_(Integer.parseInt(txtfCodeventos.getText()));
             EventosControle ev = new EventosControle ();
             ev.update(e);
         }else {
              JOptionPane.showMessageDialog(null, "Preencha todos os campos.");    
         }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
         EventosControle ev = new EventosControle ();
         if(!txtfCodeventos.getText().trim().isEmpty()){
                int Cod = Integer.parseInt(txtfCodeventos.getText());
                ev.delete(Cod);
             }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
       }
                
            
                                       
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosActionPerformed
         EventosControle ev = new EventosControle ();
         ev.selectall();
    }//GEN-LAST:event_btnDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void FormEventos () {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EVENTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EVENTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EVENTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EVENTOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EVENTOS().setVisible(true);
            }
        });
    }
    
    public eventos_ MontarEventos () {
        
           if (txtfNomedoEvento.getText().trim().isEmpty() || txtfDatadoEvento.getText().trim().isEmpty() || txtfHorarioInicio.getText().trim().isEmpty() 
               || txtfHorarioTermino.getText().trim().isEmpty() || txtfLocaldoEvento.getText().trim().isEmpty() || txtfDescricao.getText().trim().isEmpty() 
               || txtfPublicoAlvo.getText().trim().isEmpty() || txtfCapacidadeMaxima.getText().trim().isEmpty() || txtfOrganizador.getText().trim().isEmpty())
               
            { JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
                return null; 
            }
        
        
        try{      
           eventos_ e = new eventos_ ();
           e.setNome_do_Evento(txtfNomedoEvento.getText().trim());
           e.setData_do_Evento(txtfDatadoEvento.getText().trim());
           e.setHorario_Inicio(txtfHorarioInicio.getText().trim());
           e.setHorario_Termino(txtfHorarioTermino.getText().trim());
           e.setLocal_do_Evento(txtfLocaldoEvento.getText().trim());
           e.setDescricao(txtfDescricao.getText().trim());
           e.setPublico_Alvo(txtfPublicoAlvo.getText().trim());
           e.setCapacidade_Maxima(txtfCapacidadeMaxima.getText().trim());
           e.setOrganizador(txtfOrganizador.getText().trim());
        
        return e;  
        
        }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, " inválido. Digite.", "Erro", JOptionPane.ERROR_MESSAGE);
            return null;
        
     }
  }   


public void Limpar() {
        txtfCapacidadeMaxima.setText("");
        txtfDatadoEvento.setText("");
        txtfDescricao.setText("");
        txtfHorarioInicio.setText("");
        txtfHorarioTermino.setText("");
        txtfLocaldoEvento.setText("");
        txtfNomedoEvento.setText("");
        txtfOrganizador.setText("");
        txtfPublicoAlvo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JMenuItem btnDados;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbCapacidadeMaxima;
    private javax.swing.JLabel lbCodeventos;
    private javax.swing.JLabel lbDatadoEvento;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbHorarioInicio;
    private javax.swing.JLabel lbHorarioTermino;
    private javax.swing.JLabel lbLocaldoEvento;
    private javax.swing.JLabel lbNomedoEvento;
    private javax.swing.JLabel lbOrganizador;
    private javax.swing.JLabel lbPublicoAlvo;
    private javax.swing.JTextField txtfCapacidadeMaxima;
    private javax.swing.JTextField txtfCodeventos;
    private javax.swing.JTextField txtfDatadoEvento;
    private javax.swing.JTextField txtfDescricao;
    private javax.swing.JTextField txtfHorarioInicio;
    private javax.swing.JTextField txtfHorarioTermino;
    private javax.swing.JTextField txtfLocaldoEvento;
    private javax.swing.JTextField txtfNomedoEvento;
    private javax.swing.JTextField txtfOrganizador;
    private javax.swing.JTextField txtfPublicoAlvo;
    // End of variables declaration//GEN-END:variables
}
